name: benchmarks
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install custom version of pyperformance
        run: pip install "git+https://github.com/mdboom/pyperformance@codspeed#egg=pyperformance"
      - name: Create venvs
        run: PYPERFORMANCE_VENV=1 pyperformance run
      - name: Run benchmarks
        uses: CodSpeedHQ/action@main
        with:
          run: pyperformance run
